# Generated by Django 3.2.3 on 2022-03-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaptechguys', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Top', 'Top'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
